source 'http://rubygems.org/'

gem 'sinatra'
gem 'haml'
gem 'sass'
gem 'compass'
gem 'compass-960-plugin'
gem 'dm-core'
gem 'dm-timestamps'
gem 'dm-validations'
gem 'dm-aggregates'
gem 'dm-migrations'
gem 'dm-postgres-adapter'
gem 'do_postgres'
gem 'rack-flash'
gem 'sinatra-content-for'
gem 'activesupport'
gem 'i18n'
